[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "cosviewer"
version = "0.1.0"
description = "A short description of your project"
authors = [{name = "Your Name", email = "you@example.com"}]