[package]
name = "test"
version.workspace = true
edition = "2024"
publish = false

[dependencies]
cosmol_viewer_core.workspace = true
cosmol_viewer.workspace = true
eframe.workspace = true
egui_extras.workspace = true

[package.metadata.release]
release = false