[package]
name = "test"
version.workspace = true
edition = "2024"

[dependencies]
cosmol_viewer_core.workspace = true
cosmol_viewer.workspace = true
eframe.workspace = true
glam.workspace = true
egui_extras.workspace = true

