name: py-docs

on:
  push:
    tags:
      - '*'
  pull_request:
  workflow_dispatch:

jobs:
  # Build the documentation and upload the static HTML files as an artifact.
  build:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: Install python dependencies
        run: |
          uv venv .venv
          uv pip install maturin pdoc cosmol-viewer
          echo "$GITHUB_WORKSPACE/.venv/bin" >> $GITHUB_PATH

      - uses: Swatinem/rust-cache@v2
      - uses: actions-rs/toolchain@v1.0.6
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Build wasm module
        run: |
          mkdir ./crates/wasm/pkg
          touch ./crates/wasm/pkg/cosmol_viewer_wasm.js
          touch ./crates/wasm/pkg/cosmol_viewer_wasm_bg.wasm

      - name: Build Python module (develop)
        working-directory: crates/python
        run: |
          maturin develop --uv
      - name: Build documentation
        run: |
          pdoc -o docs/ cosmol_viewer
      - uses: actions/upload-pages-artifact@v3
        with:
          path: docs/

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    needs: build
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4